name: ServerSystem
version: 0.4b
author: failex234
url: failex.de
main: de.failex.serversystem.ServerSystem
commands:
   alwaysday:
   gamemode:
   online:
   ping:
   home:
   sethome:
   spawn:
   setspawn:
   warp:
   setwarp:
   sudo:
   system:
   time:
   tp:
   tphere:
   tpa:
   tpahere:
   tpaccept:
   vanish:
   unvanish: