name: ServerSystem
version: 0.1b
author: failex234
url: failex.de
main: de.failex.serversystem.ServerSystem
commands:
   alwaysday:
   gamemode:
   online:
   ping:
   home:
   sethome:
   setspawn:
   setwarp:
   spawn:
   sudo:
   system:
   time: