name: ServerSystem
version: 0.5b
author: failex234
url: felixnaumann.me
main: de.failex.serversystem.ServerSystem
commands:
   alwaysday:
   gamemode:
   online:
   ping:
   home:
   msg:
   r:
   reply:
   sethome:
   spawn:
   setspawn:
   warp:
   setwarp:
   sudo:
   system:
   time:
   tp:
   tphere:
   tpa:
   tpahere:
   tpaccept:
   vanish:
   unvanish:
